main/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.index, name='activity'),
    path('add/', views.add_activity, name='add_activity'),
    path('delete/<int:id>/', views.delete_activity, name='delete_activity'),
    path('delete-person/<int:id>/', views.delete_person, name='delete_person')
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.accordion, name='accordion'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.search_books, name='search_books'),
    path('data/', views.data, name='data'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.home_story9, name='story9_page'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

story_6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

main/models.py
from django.db import models

class Activity(models.Model):
    name = models.CharField(max_length = 50)
    class Meta:
        verbose_name_plural = "Activities"

class Person(models.Model):
    name = models.CharField(max_length = 50)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = "People"

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

main/forms.py
from django.forms import ModelForm
from .models import Person, Activity
from crispy_forms.helper import FormHelper

class ActivityForm(ModelForm):
    class Meta():
        model = Activity
        fields = '__all__'

class PersonForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['name'].label = ''

    class Meta():
        model = Person
        fields = '__all__'

story9/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Activity, Person
from .forms import ActivityForm, PersonForm
from django.contrib import messages

context = {
    "activities" : "many activities",
    "form" : "this is form",
}

def index(request):
    context["activities"] = Activity.objects.all()
    form = PersonForm(request.POST or None)
    if(form.is_valid()):
        form.save()
        return redirect('story_6:activity')

    context["form"] = form
    return render(request, "main/activity.html", context)

def add_activity(request):

    form = ActivityForm(request.POST or None)
    if(form.is_valid()):
        form.save()
        return redirect('story_6:activity')

    context["form"] = form
    return render(request, "main/add_activity.html", context)


def delete_activity(request, id):
    activity = get_object_or_404(Activity, id=id)

    activity.delete()

    return redirect('story_6:activity')

def delete_person(request, id):
    person = get_object_or_404(Person, id=id)

    person.delete()

    return redirect('story_6:activity')

story7/views.py
from django.shortcuts import render

def accordion(request):
    return render(request, "accordion.html")

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

def search_books(request):
    return render(request, "search_books.html")

def data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    response = requests.get(url)
    data = json.loads(response.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from . import forms

def sign_up(request):
    user_form = forms.CreateUserForm()
    if request.method == 'POST':
        user_form = forms.CreateUserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.save()
            
            username = user_form.cleaned_data.get('username')
            messages.success(request, f'Successfully created account with username "{username}"')
            return redirect('/story9/sign_in/')
    content = {
        'form' : user_form,
    }
    return render(request, 'sign_up.html', content)

def sign_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return redirect('/story9/')
        else:
            messages.error(request, 'Your Username or Password is Incorrect!')

    return render(request, 'sign_in.html')

def sign_out(request):
    logout(request)
    return redirect('/story9/sign_in/')    

def home_story9(request):
    if request.user.is_authenticated:
        username = request.user.username
        content = {
            'username' : username
        }
        return render(request, 'home_story9.html', content)
    return render(request, 'home_story9.html')

main/templates/main/activity.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block style %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock style %}

{% block meta %}
    <title>Story 6</title>
{% endblock meta %}

{% block content %}
    <a class="justify-content-center align-items-center" href="{% url 'story_6:add_activity' %}"><h2>Add activity</h2></a>
    {% for activity in activities reversed %}
    <div class="container">
        <div class="content-section" style="border-radius: 20px">
            <legend class="border-bottom mb-4">
                <div class="d-flex flex-row justify-content-center align-items-center">
                    <h2>{{ activity.name }}</h2>
                    <form class="m-2" action="{% url 'story_6:delete_activity' id=activity.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                    </form>
                </div>
            </legend>

            {% if activity.person_set.all %}
                <h3><b>Daftar Peserta:</b></h3>
            {% endif %}
            {% for person in activity.person_set.all %}
                <div class="m-2">
                    <h3 style="display: inline;"> {{ person.name }} </h3>
                    <form style="display: inline;" action="{% url 'story_6:delete_person' id=person.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Hapus</button>
                    </form>
                </div>
                {% empty %}
                <h3 style="text-align: center">
                    Tidak ada peserta!, silahkan klik "Tambah Peserta" untuk 
                    menambahkan peserta
                </h3>
            {% endfor %}
            
            <form action="{% url 'story_6:activity'%}" method="post">
                {% csrf_token %}
                <input type="hidden" name="activity" value="{{ activity.id }}">
                <div class="d-flex flex-row align-items-center justify-content-center m-1">
                    {{form.name|as_crispy_field}}
                    <button class="btn btn-success ml-3" type="submit">Tambah Peserta</button>
                </div>
            </form>
        </div>
    </div>
    {% empty %}
        <h3 class="m">
            Tidak ada kegiatan yang tersedia!, silahkan klik "Add Activity" untuk 
            menambahkan kegiatan
        </h3>
    {% endfor %}
{% endblock content %}

main/templates/main/add_activity.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block style %} 
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock style %}
{% block content %}
<div class="container">
    <div class="content-section" style="border-radius: 20px">
        <form action="{% url 'story_6:add_activity' %}" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"><h2>Tambah Kegiatan</h2></legend>
                {{ form|crispy }}
            </fieldset>
            <button class="btn btn-success" type="submit">Tambah Kegiatan</button>
            <a href="{% url 'story_6:activity' %}" class="btn btn-dark">Back</a>
        </form>
    </div>
</div>

{% endblock %}

{% block userscript %}
{% endblock %}

story7/templates/accordion.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/accordion.css' %}">
    <script src="{% static 'js/accordion.js' %}"></script>
    <title>Story 7 - Accordion</title>
{% endblock head %}

{% block content %}
<div class="accordion_item">
    <div class="accordion_header d-flex justify-content-between p-4">
        Aktivitas
        <div>
            <span class="button_up"><i class="fa fa-arrow-alt-circle-up"></i></span>
            <span class="button_down"><i class="fa fa-arrow-alt-circle-down"></i></span>
        </div>
    </div>
    <div class="accordion_content">
        Menanam pohon AVL 
    </div>
</div>
<div class="accordion_item">
    <div class="accordion_header d-flex justify-content-between p-4">
        Organisasi/Kepanitiaan
        <div>
            <span class="button_up"><i class="fa fa-arrow-alt-circle-up"></i></span>
            <span class="button_down"><i class="fa fa-arrow-alt-circle-down"></i></span>
        </div>
    </div>
    <div class="accordion_content">
        Staff Penunjang SIWAK 2020
    </div>
</div>    
<div class="accordion_item">
    <div class="accordion_header d-flex justify-content-between p-4">
        Prestasi
        <div>
            <span class="button_up"><i class="fa fa-arrow-alt-circle-up"></i></span>
            <span class="button_down"><i class="fa fa-arrow-alt-circle-down"></i></span>
        </div>
    </div>
    <div class="accordion_content">
        Marathon One Piece dalam 3 bulan :v
    </div>
</div>
<div class="accordion_item">
    <div class="accordion_header d-flex justify-content-between p-4">
        Hobi
        <div>
            <span class="button_up"><i class="fa fa-arrow-alt-circle-up"></i></span>
            <span class="button_down"><i class="fa fa-arrow-alt-circle-down"></i></span>
        </div>
    </div>
    <div class="accordion_content">
        Bermain Genshin Impact
    </div>
</div>
{% endblock content %}

story8/templates/search_books.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/search_books.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/search_books.js' %}"></script>
    <title>Story 8 - Ajax</title>
{% endblock head %}
 
{% block content %}
<div class="page_title">
    <h2>Search Book</h2>
</div>
<div class="d-flex flex-row align-items-center justify-content-center mb-5">
    <input id="keyword" placeholder="Search Book Here..." class="form-control ml-3">
    <button id="search_button" type="button" class="btn btn-outline-primary ml-3">Search</button>
</div>
<div id="search_result">
        
</div>
{% endblock content %}

story9/templates/home_story9.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/story9.css' %}">
    <title>Story 9</title>
{% endblock head %}
 
{% block content %}
<div class="content-section text-center" style="border-radius: 1em">
    {% if username %}
    <h2 class="text-center">Welcome, {{ username }}!</h2>
    <a href="{% url 'story9:sign_out' %}"><button class="btn btn-danger">Sign Out</button></a>
    {% else %}
    <h2>Welcome, please <a href="{% url 'story9:sign_in' %}">sign in</a> first</h2>
    {% endif %}
</div>
{% endblock content %}

story9/templates/sign_in.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/story9.css' %}">
    <title>Story 9</title>
{% endblock head %}
 
{% block content %}
<div class="content-section align-self-center m-5" style="border-radius: 1em">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <form class="col-12" method="POST">
        <legend class="border-bottom mb-4"><h2>Sign in</h2></legend>
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="material-icons">person</i></span>
            </div>
            <input type="text" name="username" placeholder="Username" class="form-control">
        </div>
        <div class="input-group mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="material-icons">vpn_key</i></span>
            </div>
            <input type="password" name="password" placeholder="Password" class="form-control"> 
        </div>
           
        <div class="text-right">
            <button type="submit" class="btn btn-outline-primary">Sign In</button>
        </div>
        <p class="text-muted" style="font-size: small;">Didn't have any account yet?  
            <a href="{% url 'story9:sign_up' %}">Sign up</a>
        </p>
    </form>
    
</div>
{% endblock content %}

story9/templates/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/story9.css' %}">
    <title>Story 9</title>
{% endblock head %}
 
{% block content %}
<div class="content-section align-self-center m-5" style="border-radius: 1em">
    <form method="POST">
        <legend class="border-bottom mb-4"><h2>Create Account</h2></legend>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-primary">Sign Up</button>
    </form>
    <p class="text-muted mt-2" style="font-size: small;">
        Already have an account?  
        <a href="{% url 'story9:sign_in' %}">Sign in</a>
    </p>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel='stylesheet' type='text/css' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
        <script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        {% block head %}{% endblock head %}
    </head>
    <body>
        <main role="main" class="container">
            {% block content %}{% endblock content %}
        </main>
    </body>
</html>